#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : oslo.vmware
Version  : 2.5.0
Release  : 30
URL      : http://tarballs.openstack.org/oslo.vmware/oslo.vmware-2.5.0.tar.gz
Source0  : http://tarballs.openstack.org/oslo.vmware/oslo.vmware-2.5.0.tar.gz
Summary  : Oslo VMware library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.vmware-python
BuildRequires : GitPython-python
BuildRequires : Jinja2
BuildRequires : PyYAML-python
BuildRequires : Pygments
BuildRequires : Sphinx-python
BuildRequires : bandit-python
BuildRequires : coverage-python
BuildRequires : discover-python
BuildRequires : docutils-python
BuildRequires : eventlet-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : hacking
BuildRequires : mox3-python
BuildRequires : netaddr
BuildRequires : netifaces-python
BuildRequires : oslo.concurrency-python
BuildRequires : oslosphinx-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyrsistent-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-mimeparse-python
BuildRequires : python-mock-python
BuildRequires : python3-dev
BuildRequires : requests-python
BuildRequires : setuptools
BuildRequires : suds-jurko-python
BuildRequires : testrepository-python
BuildRequires : testscenarios
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : tox
BuildRequires : traceback2-python
BuildRequires : unittest2-python
BuildRequires : urllib3-python
BuildRequires : virtualenv

%description
===================================================
oslo.vmware --- VMware support code for OpenStack
===================================================

%package python
Summary: python components for the oslo.vmware package.
Group: Default
Requires: PyYAML-python
Requires: eventlet-python
Requires: netaddr
Requires: oslo.concurrency-python
Requires: requests-python
Requires: suds-jurko-python
Requires: urllib3-python

%description python
python components for the oslo.vmware package.


%prep
%setup -q -n oslo.vmware-2.5.0

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
